name: Rlease

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    release-dev:
        uses: ./.github/workflows/resused-release.yaml
        permissions:
          actions: read
          contents: write
          id-token: write
          issues: write
        with:
            environment: dev
        secrets: inherit